version: '3.8'

services:
  oroma-tv-api:
    build: .
    image: oroma-tv-api:latest
    container_name: oroma-tv-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - APP_MODULE=main:app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/app-data"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - oroma-network

networks:
  oroma-network:
    driver: bridge